services:
  - type: web
    name: wizzy-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    healthCheckPath: /health
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: wizzy-bot-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.0

databases:
  - name: wizzy-bot-db
    databaseName: wizzy_bot
    user: wizzy_user
    plan: free
